"""description of migration

Revision ID: 42859ade802a
Revises: 65b8f2bb2572
Create Date: 2025-03-13 22:43:49.795099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42859ade802a'
down_revision: Union[str, None] = '65b8f2bb2572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_logs', 'collector_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collection_logs', 'recycling_center_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collection_logs', 'waste_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collectors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('collectors', 'contact_info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('collectors', 'gender')
    op.alter_column('recycling_centers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recycling_centers', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('waste_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('waste_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('waste_items', 'weight',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waste_items', 'weight',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('waste_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('waste_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recycling_centers', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recycling_centers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('collectors', sa.Column('gender', sa.VARCHAR(), nullable=True))
    op.alter_column('collectors', 'contact_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('collectors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('collection_logs', 'waste_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collection_logs', 'recycling_center_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collection_logs', 'collector_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
