"""added gender column

Revision ID: 65b8f2bb2572
Revises: 764f966a9434
Create Date: 2025-03-13 12:46:19.995982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b8f2bb2572'
down_revision: Union[str, None] = '764f966a9434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collectors', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collectors', 'gender')
    # ### end Alembic commands ###
